### ISSUE TITLE
Undefined name 'loss' in models/dense_net.py

### ISSUE THREAD

**Issue by cclauss** [noahfl/densenet-sdr#6]
flake8 testing of https://github.com/noahfl/densenet-sdr on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./models/dense_net.py:476:51: F821 undefined name 'loss'
            ([str(v) for _, v in grads_and_vars], loss))
                                                  ^
1     F821 undefined name 'loss'
1
```

**Comment by noahfl** [comment]
Thanks for the heads up! I've fixed this in the latest update.
